version: '3.8'
services:
  postgress:
    image: postgres:14-alpine
    container_name: postgres-dev
    restart: always
    ports:
      - '${PG_PORT}:${PG_PORT}'
    environment:
      - POSTGRES_USERNAME=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    volumes:
      - ${HOME}/postgres-data/:/var/lib/postgresql/data
  # server:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.dev
  #   container_name: time-tracker-dev
  #   restart: always
  #   ports:
  #     - '${PORT}:${PORT}'
  #   volumes:
  #     - ./:/opt/app/time-tracker
